NEST-537: Upgrading DotNest to OC 2.1.3
Lombiq/Show-Orchard-Theme pull request #12
Opened 2024-12-12 22:29 UTC by BenedekFarkas

2025-02-22 02:35 UTC, Piedone requested changes
Note to self: test this once setup works.

2025-02-22 02:35 UTC, Piedone commented on ShowOrchard.Theme/Recipes/ShowOrchard.MediaTheme.recipe.json
This shouldn't be added to the repo, see the Teams convo.

2025-03-02 00:40 UTC, Piedone commented
How did you test this, given that also the standard setup from the Sites SDK is broken?

Note to self: check https://github.com/Lombiq/DotNest-Core-Sites-SDK/pull/86/files/e66759c896fe757a7ad796d4187182234c3dd790..aa2b34210a5486cefee469ea1293273bbd7a5c31#diff-602a6af11ba7f173cb2a490aab9fe35bc2e493dd6aaf4e9263e3ad1398fb5778 too.

2025-03-03 15:09 UTC, BenedekFarkas commented
> How did you test this, given that also the standard setup from the Sites SDK is broken?
> 
> Note to self: check https://github.com/Lombiq/DotNest-Core-Sites-SDK/pull/86/files/e66759c896fe757a7ad796d4187182234c3dd790..aa2b34210a5486cefee469ea1293273bbd7a5c31#diff-602a6af11ba7f173cb2a490aab9fe35bc2e493dd6aaf4e9263e3ad1398fb5778 too.

Regarding the code itself of media theme deployment? When you set up from DotNest Tenants Core, then you're using the Media Theme, so AFAIK that covers both (and the UI tests are all passing).

2025-03-03 20:58 UTC, Piedone commented
Yeah, while deploying DotNest Tenants Core doesn't deploy the Media Themes, the tests are relevant, since they do use the latest themes.

2025-03-03 21:00 UTC, Piedone commented on ShowOrchard.Theme/Views/Layout.liquid
> +    {% google_tag property_id: "G-C8EEHMLQLP", cookie_domain: "auto" %}<!-- #spell-check-ignore-line -->
Shouldn't this display something locally too? The template's changes show up for me, but this displays nothing.

2025-03-03 21:44 UTC, BenedekFarkas commented on ShowOrchard.Theme/Views/Layout.liquid
> +    {% google_tag property_id: "G-C8EEHMLQLP", cookie_domain: "auto" %}<!-- #spell-check-ignore-line -->
Summoning @sarahelsaig, because these are her changes from the `task/system-text-json-migration` branch.

2025-03-04 14:32 UTC, sarahelsaig commented on ShowOrchard.Theme/Views/Layout.liquid
> +    {% google_tag property_id: "G-C8EEHMLQLP", cookie_domain: "auto" %}<!-- #spell-check-ignore-line -->
No, it never displayed anything outside of production mode. This was true [when it was in Lombiq.BaseTheme](https://github.com/Lombiq/Orchard-Base-Theme/pull/122/files#diff-736f0d6f936f738922808c24b7f8ee8d530338dcfd6f53c30efc0eb1e7ce188aL14) and didn't change [when the GoogleTag shape was moved into HE](https://github.com/Lombiq/Helpful-Extensions/commit/3f312f60f2129b26cf4fb434358ef3550b31a67d#diff-2dcab13645aaab146c25b77b298995e1e985e2ebc80f344927e82523c3e460baR14) (btw both `{% google_tag %}` for Liquid and `<google-tag>` for Razor are just friendly wrappers around the shape tag helper with pre-defined arguments).

2025-03-04 21:05 UTC, Piedone commented on ShowOrchard.Theme/Views/Layout.liquid
> +    {% google_tag property_id: "G-C8EEHMLQLP", cookie_domain: "auto" %}<!-- #spell-check-ignore-line -->
OK then!

2025-03-04 21:05 UTC, Piedone approved these changes

2025-03-04 21:13 UTC, merged